//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cyclon.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cyclon.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 404 Page not found.
        /// </summary>
        internal static string _404 {
            get {
                return ResourceManager.GetString("404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 500 Internal error.
        /// </summary>
        internal static string _500 {
            get {
                return ResourceManager.GetString("500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account created successfully! Log in....
        /// </summary>
        internal static string ACCOUNT_CREATED_SUCCESS {
            get {
                return ResourceManager.GetString("ACCOUNT_CREATED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alert!.
        /// </summary>
        internal static string alert {
            get {
                return ResourceManager.GetString("alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contact.
        /// </summary>
        internal static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a $[0] $[1] to $[2] km from you has been detected.
        /// </summary>
        internal static string contentAlert {
            get {
                return ResourceManager.GetString("contentAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm password.
        /// </summary>
        internal static string cpassword {
            get {
                return ResourceManager.GetString("cpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The data can not be empty.
        /// </summary>
        internal static string DATA_EMPTY {
            get {
                return ResourceManager.GetString("DATA_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The data invalid.
        /// </summary>
        internal static string DATA_INVALID {
            get {
                return ResourceManager.GetString("DATA_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The data must not be more than 50 character.
        /// </summary>
        internal static string DATA_LONG {
            get {
                return ResourceManager.GetString("DATA_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The data can only have letters and / or spaces.
        /// </summary>
        internal static string DATA_SPACES_AND_LETTERS {
            get {
                return ResourceManager.GetString("DATA_SPACES_AND_LETTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The data submited is invalid.
        /// </summary>
        internal static string DATA_SUBMITED_INVALID {
            get {
                return ResourceManager.GetString("DATA_SUBMITED_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a the tropical depression.
        /// </summary>
        internal static string dt {
            get {
                return ResourceManager.GetString("dt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email format is invalid.
        /// </summary>
        internal static string EMAIL_FORMAT {
            get {
                return ResourceManager.GetString("EMAIL_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The email entered is already registered.
        /// </summary>
        internal static string EMAIL_REGISTERED {
            get {
                return ResourceManager.GetString("EMAIL_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify current email before changing.
        /// </summary>
        internal static string EMAIL_VERIFY {
            get {
                return ResourceManager.GetString("EMAIL_VERIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a the hurricaine.
        /// </summary>
        internal static string h {
            get {
                return ResourceManager.GetString("h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you have already an account? Log in.
        /// </summary>
        internal static string has_account {
            get {
                return ResourceManager.GetString("has_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data updated succesfully.
        /// </summary>
        internal static string INFO_UPDATED {
            get {
                return ResourceManager.GetString("INFO_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data updated succesfully. Log in again.
        /// </summary>
        internal static string INFO_UPDATED_RELOGIN {
            get {
                return ResourceManager.GetString("INFO_UPDATED_RELOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your IP address cannot be located.
        /// </summary>
        internal static string IP_NOT_FOUND {
            get {
                return ResourceManager.GetString("IP_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last Name.
        /// </summary>
        internal static string lastName {
            get {
                return ResourceManager.GetString("lastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loading.
        /// </summary>
        internal static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a en.
        /// </summary>
        internal static string location {
            get {
                return ResourceManager.GetString("location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in....
        /// </summary>
        internal static string LOG_IN {
            get {
                return ResourceManager.GetString("LOG_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in with Facebook.
        /// </summary>
        internal static string login_facebook {
            get {
                return ResourceManager.GetString("login_facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in with Google.
        /// </summary>
        internal static string login_google {
            get {
                return ResourceManager.GetString("login_google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login in Cyclon.
        /// </summary>
        internal static string loginCyclon {
            get {
                return ResourceManager.GetString("loginCyclon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logout.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Map.
        /// </summary>
        internal static string map {
            get {
                return ResourceManager.GetString("map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The passwords do not match.
        /// </summary>
        internal static string PASSWORD_DONT_MATCH {
            get {
                return ResourceManager.GetString("PASSWORD_DONT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password can not be empty.
        /// </summary>
        internal static string PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password is invalid.
        /// </summary>
        internal static string PASSWORD_INCORRECT {
            get {
                return ResourceManager.GetString("PASSWORD_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password must not be more than 50 characters.
        /// </summary>
        internal static string PASSWORD_LONG {
            get {
                return ResourceManager.GetString("PASSWORD_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password must have more than 8 characters.
        /// </summary>
        internal static string PASSWORD_SHORT {
            get {
                return ResourceManager.GetString("PASSWORD_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password updated, log in.
        /// </summary>
        internal static string PASSWORD_UPDATED {
            get {
                return ResourceManager.GetString("PASSWORD_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your current password.
        /// </summary>
        internal static string PASSWORD_VERIFY {
            get {
                return ResourceManager.GetString("PASSWORD_VERIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Receive alerts.
        /// </summary>
        internal static string receiveAlerts {
            get {
                return ResourceManager.GetString("receiveAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register.
        /// </summary>
        internal static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REGISTER.
        /// </summary>
        internal static string register_page {
            get {
                return ResourceManager.GetString("register_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register in Cyclon.
        /// </summary>
        internal static string registerCyclon {
            get {
                return ResourceManager.GetString("registerCyclon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cyclon settings.
        /// </summary>
        internal static string settingCyclon {
            get {
                return ResourceManager.GetString("settingCyclon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Location updated succesfully.
        /// </summary>
        internal static string SUCCESS_LOCATION {
            get {
                return ResourceManager.GetString("SUCCESS_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid token.
        /// </summary>
        internal static string TOKEN_INVALID {
            get {
                return ResourceManager.GetString("TOKEN_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a the tropical storm.
        /// </summary>
        internal static string tt {
            get {
                return ResourceManager.GetString("tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tweets.
        /// </summary>
        internal static string tweets {
            get {
                return ResourceManager.GetString("tweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update Information.
        /// </summary>
        internal static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update Data.
        /// </summary>
        internal static string updateData {
            get {
                return ResourceManager.GetString("updateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update Location.
        /// </summary>
        internal static string updateLocation {
            get {
                return ResourceManager.GetString("updateLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update password.
        /// </summary>
        internal static string updatePassword {
            get {
                return ResourceManager.GetString("updatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account does not exist.
        /// </summary>
        internal static string USER_NOT_EXIST {
            get {
                return ResourceManager.GetString("USER_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user is not exist.
        /// </summary>
        internal static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
    }
}
